### PR TITLE
Upgrade OpenTK 3.0.1

### PR DESCRIPTION
**Pull request by MutterOberin**
As mentioned in #43 this would upgrade to OpenTK 3.0.1

### CODE REVIEW

**Comment by opcon** [comment]
Hi @MutterOberin 

Thank you for this pull request!

It looks like you have upgraded to OpenTK 3.0.1 without using the `paket.lock` and `paket.dependencies`, but rather with NuGet.

Because of this, I can't merge the pullrequest as is - but I will fix it up and update to OpenTK 3.0.1 shortly

Cheers

**Comment by MutterOberin** [comment]
Hey @opcon 

Ufff... Sorry. I was not looking at these. I can also quickly update the pr to use paket.lock and paket.dependecies.

**Comment by opcon** [comment]
Hi @MutterOberin,

I've just released version 4.5 of QuickFont, which among a few other things, is updated to OpenTK 3.0.1.

Sorry this took me so long to get too, and thanks for the PR

**Comment by MutterOberin** [comment]
Hi @opcon,

That sounds good! Thank you very much for the work!

**Pull request closed without merging**
